---
- name: install slapd
  hosts: ldapserver
  tasks:
    - name: set internal for slapd
      debconf:
        name: slapd
        question: internal/adminpw
        value: admin
        vtype: password

    - name: set internal/generated_adminpw for slapd
      debconf:
        name: slapd
        question: internal/generated_adminpw
        value: admin
        vtype: password

    - name: set password1 for slapd
      debconf:
        name: slapd
        question: slapd/password1
        value: admin
        vtype: password
    
    - name: set password2 for slapd
      debconf:
        name: slapd
        question: slapd/password2
        value: admin
        vtype: password
    
    - name: set purge_database for slapd
      debconf:
        name: ldap-utils
        question: slapd/purge_database
        value: false
        vtype: boolean
    
    - name: set domain for slapd
      debconf:
        name: ldap-utils
        question: slapd/domain
        value: ldap.com
        vtype: string

    - name: set invaild_config for slapd
      debconf:
        name: ldap-utils
        question: slapd/invaild_config
        value: true
        vtype: boolean

    - name: set move_old_database for slapd
      debconf:
        name: ldap-utils
        question: slapd/move_old_database
        value: true
        vtype: boolean

    - name: set backend for slapd
      debconf:
        name: ldap-utils
        question: slapd/backend
        value: MDB
        vtype: select

    - name: set allow_ldap_v2 for slapd
      debconf:
        name: ldap-utils
        question: slapd/allow_ldap_v2
        value: false
        vtype: boolean

    - name: set no_configuration for slapd
      debconf:
        name: ldap-utils
        question: slapd/no_configuration
        value: false
        vtype: boolean

    - name: set dump_database for slapd
      debconf:
        name: ldap-utils
        question: slapd/dump_database
        value: when needed
        vtype: select

    - name: install slapd
      apt:
        update_cache: yes
        name: '{{ item }}'
        state: present
      with_items:
        - slapd
        - ldap-utils
        - phpldapadmin

    - name: Pass options to dpkg on run
      dpkg_selections:
        name: slapd
        selection: hold

    - name: edit ldap.conf
      lineinfile:
        path: /etc/ldap/ldap.conf
        line: '{{ item }}'
        owner: root
        group: root
        state: present
        mode: 0644
      with_items:
        - 'BASE  dc=ldap,dc=com'
        - 'URI  ldap://localhost:389'